/**
 * Regenerates src/lib/scripture/kjv/*.json from the es-kjv package
 * (KJV 1769 text, released into the public domain).
 *
 *   npx tsx scripts/generate-kjv.ts
 *
 * Output: one file per book, [chapter][verse] -> text. Words the KJV prints
 * in italics (supplied by the translators) keep es-kjv's [brackets]; the app
 * renders them in italics. Paragraph marks ("#") are dropped.
 *
 * Cross-checked when this data was added: same versification as the KJV
 * table in books.ts, and word-for-word identical to CrossWire's KJV apart
 * from spelling conventions, with one exception (Josh 19:2 "or Sheba",
 * where es-kjv matches the printed KJV). The tests re-check versification.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";
import { BOOKS } from "../src/lib/scripture/books";

const require = createRequire(import.meta.url);
const source = readFileSync(join(require.resolve("es-kjv/package.json"), "..", "json", "verses-1769.js"), "utf8");

// Lines look like: "Genesis 1:1":"In the beginning ...",
const ENTRY = /^"(.+?) (\d+):(\d+)":("(?:[^"\\]|\\.)*"),?$/gm;
const byBook = new Map<string, string[][]>();
const order: string[] = [];
for (const m of source.matchAll(ENTRY)) {
  const [, name, ch, v, quoted] = m;
  if (!byBook.has(name)) {
    byBook.set(name, []);
    order.push(name);
  }
  const chapters = byBook.get(name)!;
  const c = Number(ch) - 1;
  chapters[c] ??= [];
  if (chapters[c].length !== Number(v) - 1) throw new Error(`Out of order: ${name} ${ch}:${v}`);
  const text = (JSON.parse(quoted) as string).replace(/#\s*/g, "").trim();
  chapters[c].push(text);
}

if (order.length !== BOOKS.length) throw new Error(`Expected ${BOOKS.length} books, got ${order.length}`);
const outDir = join(import.meta.dirname, "..", "src", "lib", "scripture", "kjv");
let verses = 0;
BOOKS.forEach((book, i) => {
  const chapters = byBook.get(order[i])!;
  const shape = chapters.map((c) => c.length);
  if (JSON.stringify(shape) !== JSON.stringify(book.verses)) {
    throw new Error(`${book.id} (${order[i]}): versification differs from books.ts`);
  }
  verses += shape.reduce((a, b) => a + b, 0);
  writeFileSync(join(outDir, `${book.id}.json`), JSON.stringify(chapters));
});
// Static import() per book, so the bundler includes every book but each is
// only parsed when a verse from it is first shown.
const loaders = BOOKS.map((b) => `  ${JSON.stringify(b.id)}: () => import("./${b.id}.json"),`).join("\n");
writeFileSync(
  join(outDir, "index.ts"),
  `// GENERATED by scripts/generate-kjv.ts. Do not edit.\n` +
    `type Chapters = string[][];\n` +
    `export const KJV_BOOKS: Record<string, () => Promise<{ default: Chapters }>> = {\n${loaders}\n};\n`,
);
console.log(`Wrote ${BOOKS.length} books, ${verses} verses to ${outDir}`);
